### ISSUE TITLE
New users do not receive initial welcome email upon registration.

### ISSUE THREAD

**Issue by kriziabel** [sass-team/sass-app#106]
Hello,

I would like to request to have something fixed for the SASS App because the new learning facilitators do not have codes and cannot access the app which results in them not being able to see whether they have appointments with students or not.

Thank you in advance.

**Comment by rdok** [comment]
Hi @kriziabel,

Thank for you posting this issue. 

Are you saying when adding a new learning facilitator, they do not the corresponding emails? This emails, if I remember correctly, will prompt them to set a password. So then they can access the app. 

Does this makes sense?

**Comment by kriziabel** [comment]
Yes, they did not get a corresponding email and therefore they did not get prompted into setting up a password. Which results in them not being able to access the app to see their appointments.

**Comment by rdok** [comment]
Ahh sorry about that @kriziabel , I had assumed this fixed from https://github.com/sass-team/sass-app/issues/105

Can you do one thing for me please, before I start debugging this? 

Can you check that those emails are not in the spam folder?

**Comment by kriziabel** [comment]
I checked the spam folder. there are no emails there.

**Comment by kriziabel** [comment]
That is totally fine!

**Comment by rdok** [comment]
HI @kriziabel

I verified both the welcome email, as well as the recover email work as expected. Please note, our users will now receive those emails from dev.sass.ms@gmail.com.

What I did not verify is the daily appointments emails. Would you mind keeping an eye for this?
