### ISSUE TITLE
Add labels for appointment status.

### ISSUE THREAD

**Issue by Geoskar** [sass-team/sass-app#62]
**Description:** Currently on appointments/add only a single label exists for appointements. There should exist labels for appointments status.   

**Location:** 
- /appointments/add
- /appointments/calendar  

**TODO:**  
- Add labels on bar of calendar.
- Grey: pending appointments
- Red: canceled appointments.
- Green: successfuly done appointments. 

**Done:**
- Add labels on bar of calendar.
- Grey: pending appointments.

*Original comment: the labels of appointments should be RED color as indicated in the description and not GREY*

**Comment by rdok** [comment]
Actually this color represents pending.
- Grey: pending appointments
- Red: canceled appointments.
- Green: successfuly done appointments.
Any idea would be to make the label of appointments transparent and 'hoverable'. That is when the user hovers over this label then show a pop explaining their color using the above 3 items code.

What do you think?

**Comment by Geoskar** [comment]
no transparent or hoverable plz.

Let the colors of appointments be what you suggested but informing about the label-colors on top.

**Comment by rdok** [comment]
OK. 
Something like this @Geoskar ?

![labels-demo](https://cloud.githubusercontent.com/assets/4212119/5900585/9808ae70-a573-11e4-95c1-2920968ec101.jpg)

**Comment by Geoskar** [comment]
Yes perfect. same in appointments/calendar

But can you make them clickable as it is in appointments/add?

**Comment by rdok** [comment]
Roger that.
