### ISSUE TITLE
Appointments with more than one student

### ISSUE THREAD

**Issue by spvallianos** [sass-team/sass-app#71]
When trying to add an appointment with three (3) students we encountered 2 issues:
i. The search bar for the instructor was messed up/couldn't search and we had to manually browse it for finding the instructor.
ii. After adding the 2 extra students, selecting an instructor and finalizing all the details of the appointment and while trying to add the appointment an error came ("An instructor is required for each student.") up that said that we must input an instructor for each student but there was no relevant field/option to do this.

**Comment by rdok** [comment]
Tested on production server (sass-app.in). Works fine. I'll try to some more time fix the UI later.
Also please, make the add more student operation your last one.
Again I'll fix not blocker issue as soon as I find some time.

Grats on being the first one to official declare an issue Spyro :+1:
