### ISSUE TITLE
academia/students/edit

### ISSUE THREAD

**Issue by Geoskar** [sass-team/sass-app#78]
Mobile, Major, CI, Credits fields display wrong data when trying to update a student

**Comment by Geoskar** [comment]
solved

**Comment by rdok** [comment]
@Geoskar can you pass here the commit with this fix? That is, did you merged it with develop. Axx, nevermind, found it! http://bit.ly/1DOa1kx  
Btw, this is cool; you can [close issues with a commit](https://help.github.com/articles/closing-issues-via-commit-messages/).

**Comment by Geoskar** [comment]
Riz i took the initiative to see this issue with the edit of students while
i was on the branch of search-page but when i commited the message was
about the issue.
Στις 5 Μαρ 2015 6:15 ΠΜ, ο χρήστης "Rizart Dokollari" <
notifications@github.com> έγραψε:

**Comment by rdok** [comment]
Axxx, got it.  
Yes. And the cool thing would be this issue would be solved by github automatically when we merged the feature/search branch -> develop -> master. That's why it's so awesome to solve issues  with [git message](https://help.github.com/articles/closing-issues-via-commit-messages/)
